### ISSUE TITLE
API input Objects should be represented with windows rather than many open fields

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/kaltura-api-recipes#22]
API input Objects should be represented with windows rather than many open fields.
![filer-pager-object-windows](https://cloud.githubusercontent.com/assets/150514/13553522/409a9a66-e395-11e5-9bbb-8d2a0cb571f4.png)

See the TestMe Console as reference:
![objects-should-be-windows](https://cloud.githubusercontent.com/assets/150514/13553523/465af1b2-e395-11e5-9477-0368debe336f.png)

**Comment by rbren** [comment]
Is the hope here to better group filter/pager inputs? I don't have quite as much screen real estate as you do in the TestMe console, but happy to play with the UI a bit to better group these inputs.

**Comment by rbren** [comment]
How's this?

![screen shot 2016-03-06 at 12 13 18 pm](https://cloud.githubusercontent.com/assets/7611973/13555668/e456d6d4-e394-11e5-9056-c32bfffdd7a0.png)

**Comment by zoharbabin** [comment]
I like the expand/collapse option (actually, i think it's better than windows).
However, do make sure to address the main requests too - 
1. it should allow for nested objects to be used as nested expand/collapse menus.
2. it should allow to chose the correct objects (e.g. filter may have several options, etc.)

For example; in the above TestMe Console screenshot, you see that I used media.list action, with a Filter of type KalturaMediaEntryFilter, inside, I am using the advancedSearch field and setting it to a KalturaSearchCondition object, which then also expands into two fields.
See this use-case as reference example - [Searching for entries using custom-metadata fields/values](http://knowledge.kaltura.com/node/269).

**Comment by rbren** [comment]
I'm having an issue here due to circular references - e.g. KalturaOperationResource (a subclass of KalturaContentResource) has a `resource` parameter that can be nested KalturaOperationResources, and this nesting can occur infinitely (see screenshot of testme console)

The best option I can think of to handle these cases in the UI is to simply limit the number of levels of nesting. What do you think?

![screen shot 2016-03-07 at 3 06 48 pm](https://cloud.githubusercontent.com/assets/7611973/13581767/7f81aa08-e476-11e5-875c-9cc7ccaa8eb8.png)
